### ISSUE TITLE
intermitttent test failures

### ISSUE THREAD

**Issue by rathann** [mnemosyne-proj/mnemosyne#108]
Two tests fail when running the test suite, but not all the time:
```
$ python3 -m nose tests/test_controller.py:TestController.test_retain_only_child_tags tests/test_database.py:TestDatabase.test_tags_for_cards
FF
======================================================================
FAIL: test_controller.TestController.test_retain_only_child_tags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Mnemosyne-2.6.1/tests/test_controller.py", line 206, in test_retain_only_child_tags
    assert c._retain_only_child_tags(["a", "b"]) == ["a", "b"]
AssertionError

======================================================================
FAIL: test_database.TestDatabase.test_tags_for_cards
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Mnemosyne-2.6.1/tests/test_database.py", line 691, in test_tags_for_cards
    assert tag._id in [2]
AssertionError

----------------------------------------------------------------------
```

Re-running makes the tests pass and the fail again in subsequent try. This happens with both python 3.6.8 (Fedora 28) and 3.7.2 (Fedora 29, Fedora Rawhide). It's reproducible, but not every time. They either both pass or both fail.

The failures were reported before in #71 .

**Comment by woohgit** [comment]
I think I've fixed this via PR 110.

**Comment by woohgit** [comment]
It seems I just fixed `test_retain_only_child_tags` the `test_tags_for_cards` is still failing. I'll have a look at it.

**Comment by woohgit** [comment]
Ok, so when it comes to the `test_tags_for_cards` test suite: the tag with the name `b` sometimes is created before the `a`, so the order is mixed up.

It seems I can address this easily by returning a sorted list at the end of the `default_controller._retain_only_child_tags()`
