### ISSUE TITLE
Python 3.9's array.array doesn't have a tostring method

### ISSUE THREAD

**Issue by SnarkBoojum** [mnemosyne-proj/mnemosyne#176]
msgfmt.py doesn't run with more recent Python versions:
```
python3 ./msgfmt.py -o ../mo/cs/LC_MESSAGES/mnemosyne.mo cs.po
Traceback (most recent call last):
  File "/home/jpuydt/Debian/build/mnemosyne-2.7.3+ds1/po/./msgfmt.py", line 236, in <module>
    main()
  File "/home/jpuydt/Debian/build/mnemosyne-2.7.3+ds1/po/./msgfmt.py", line 232, in main
    make(filename, outfile)
  File "/home/jpuydt/Debian/build/mnemosyne-2.7.3+ds1/po/./msgfmt.py", line 199, in make
    output = generate()
  File "/home/jpuydt/Debian/build/mnemosyne-2.7.3+ds1/po/./msgfmt.py", line 92, in generate
    output += array.array("i", offsets).tostring()
AttributeError: 'array.array' object has no attribute 'tostring'
```

**Comment by SnarkBoojum** [comment]
Here is a trivial [patch](https://github.com/mnemosyne-proj/mnemosyne/files/5601176/fix_975820.txt) fixing the issue.

**Comment by pbienst** [comment]
Fixed, thanks!
