### ISSUE TITLE
'collections' has no attribute 'Callable' error while syncing database

### ISSUE THREAD

**Issue by Chazoshtare** [mnemosyne-proj/mnemosyne#230]
I have a headless server that I'm using as a main sync server for my mnemosyne cards. Currently, whenever I try to sync with it, it fails with the following error:
```
AttributeError("module 'collections' has no attribute 'Callable'")
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cheroot/server.py", line 1300, in communicate
    req.respond()
  File "/usr/lib/python3.10/site-packages/cheroot/server.py", line 1090, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3.10/site-packages/cheroot/wsgi.py", line 140, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/lib/python3.10/site-packages/openSM2sync/server.py", line 115, in wsgi_app
    status, method, args  = self.get_method(environ)
  File "/usr/lib/python3.10/site-packages/openSM2sync/server.py", line 168, in get_method
    if hasattr(self, method) and isinstance(getattr(self, method), collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'
```

Python version: `Python 3.10.7`
Mnemosyne version: `Mnemosyne 2.8`

**Comment by pbienst** [comment]
This should be solved in the latest released version.
