### ISSUE TITLE
error installing on windows with pip

### ISSUE THREAD

**Issue by andrewchenshx** [mnemosyne-proj/mnemosyne#258]
os: win10 64bit
python: 3.10.11
steps:
following the instruction [here](https://mnemosyne-proj.org/download-mnemosyne.php)
input `pip install mnemosyne-proj` to the cmd window,
the result is as:
Building wheels for collected packages: mnemosyne-proj
  Building wheel for mnemosyne-proj (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for mnemosyne-proj (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-7_7jiou9\mnemosyne-proj_5e76b5f104c54dcb88738f2a5b0b995e\poetry-build.py", line 3, in <module>
          subprocess.run(["make", "build"])
        File "C:\software\python310\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\software\python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\software\python310\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      Traceback (most recent call last):
        File "C:\Users\Administrator\py_envs\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\py_envs\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Administrator\py_envs\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s66p3b5e\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s66p3b5e\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s66p3b5e\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 123, in build
          self._build(zip_file)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s66p3b5e\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s66p3b5e\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 262, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\software\python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/Users/Administrator/py_envs/py310/Scripts/python.exe', 'poetry-build.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mnemosyne-proj
Failed to build mnemosyne-proj
ERROR: Could not build wheels for mnemosyne-proj, which is required to install pyproject.toml-based projects

**Comment by pbienst** [comment]
The relevant part is `FileNotFoundError: [WinError 2] The system cannot find the file specified' 

So, there's something missing on your system, probably a dependency or so. The problem is that pip builds are very difficult to debug to figure out what is missing, because run from autogenerated temporary files that you can't easily edit.

So I'm afraid this is a bit beyond my capabilities at the moment...
