### ISSUE TITLE
mnemosyne fails to start, crashes with pkg_resources.ResolutionError: Script 'scripts/mnemosyne' not found in metadata

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#69]
```
Traceback (most recent call last):
  File "/usr/local/bin/mnemosyne", line 4, in <module>
    __import__('pkg_resources').run_script('Mnemosyne==2.6', 'mnemosyne')
  File "/home/mateusz/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mateusz/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/mnemosyne' not found in metadata at '/home/mateusz/Install/Mnemosyne-2.6/Mnemosyne.egg-info'
```

on the attempt to run Mnemosyne 2.6 installed from source on

```
uname -a
Linux grisznak 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

install log: https://gist.github.com/matkoniecz/a82135679ebff0bd40fe83d0e77d5a27

**Comment by matkoniecz** [comment]
install log: https://gist.github.com/matkoniecz/a82135679ebff0bd40fe83d0e77d5a27

**Comment by matkoniecz** [comment]
attempting to install recent master version results in 
```
Traceback (most recent call last):
  File "/usr/local/bin/mnemosyne", line 4, in <module>
    __import__('pkg_resources').run_script('Mnemosyne==2.6.1', 'mnemosyne')
  File "/home/mateusz/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mateusz/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/mnemosyne' not found in metadata at '/home/mateusz/Install/mnemosyne/Mnemosyne.egg-info'
```

**Comment by pbienst** [comment]
I no longer use Linux for development, so I can't easily check, but I suggest after you checkout from git, you first do 'make distrib' to create a tarball, and then install from that tarball.

**Comment by matkoniecz** [comment]
Thanks for the reply! Is `make distrib` supposed to need sudo?

```
# Erase previous directories to make sure we're clean.
rm -rf dist
rm: cannot remove 'dist/Mnemosyne-2.6.1-py3.5.egg': Permission denied
makefile:99: recipe for target 'distrib' failed
make: *** [distrib] Error 1
```

**Comment by pbienst** [comment]
It is, if it needs to delete directories which were previously created with sudo :-)

**Comment by pbienst** [comment]
Let's consolidate all the discussion #73
