### ISSUE TITLE
failing tests in the master

### ISSUE THREAD

**Issue by matkoniecz** [mnemosyne-proj/mnemosyne#71]
```
python3 -m nose tests
...............................................................................F.........................................................F.................................................................................................................................................................................................................................Wrong username or password.......................Sync failed, the next sync will be a full sync.You have manually copied the data directory before sync. Sync needs to start from an empty database..Sync failed, the next sync will be a full sync.
Traceback (innermost last):
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 682, in get_sync_finish
    self.close_session_with_token(session_token)
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 184, in close_session_with_token
    session.close()
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 61, in close
    self.client_info["machine_id"])
  File "/home/mateusz/Install/mnemosyne/mnemosyne/libmnemosyne/databases/SQLite_sync.py", line 123, in update_last_log_index_synced_for
    raise RuntimeError(_("Missing plugins for card types."))
 RuntimeError: Missing plugins for card types.
Internal server error

Traceback (innermost last):
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 682, in get_sync_finish
    self.close_session_with_token(session_token)
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 184, in close_session_with_token
    session.close()
  File "/home/mateusz/Install/mnemosyne/openSM2sync/server.py", line 61, in close
    self.client_info["machine_id"])
  File "/home/mateusz/Install/mnemosyne/mnemosyne/libmnemosyne/databases/SQLite_sync.py", line 123, in update_last_log_index_synced_for
    raise RuntimeError(_("Missing plugins for card types."))
 RuntimeError: Missing plugins for card types.
Sync failed, the next sync will be a full sync..
Traceback (innermost last):
  File "/home/mateusz/Install/mnemosyne/openSM2sync/client.py", line 165, in sync
    result = self.put_client_log_entries()
 TypeError: <lambda>() missing 1 required positional argument: 'x'
Sync failed, the next sync will be a full sync.Sync failed, the next sync will be a full sync...........................................Sync failed, the next sync will be a full sync.Sync cycle detected. Sync through intermediate partner.................................................
======================================================================
FAIL: test_controller.TestController.test_retain_only_child_tags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mateusz/Install/mnemosyne/tests/test_controller.py", line 206, in test_retain_only_child_tags
    assert c._retain_only_child_tags(["a", "b"]) == ["a", "b"]
AssertionError

======================================================================
FAIL: test_database.TestDatabase.test_tags_for_cards
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mateusz/Install/mnemosyne/tests/test_database.py", line 691, in test_tags_for_cards
    assert tag._id in [2]
AssertionError

----------------------------------------------------------------------
Ran 477 tests in 82.960s

FAILED (failures=2)
```

**Comment by pbienst** [comment]
Strange, I cannot reproduce this in my own installation. Also, github's own tests are running fine, as you can see from the front page...

So I guess this is something related to your own setup. Perhaps it's worthwhile double-checking that there are no files from an old installation interfering?

**Comment by matkoniecz** [comment]
> So I guess this is something related to your own setup.

Likely, it is worth investigating whatever Mnemosyne is not supporting valid install or is it result of Mnemosyne not installed properly.

> that there are no files from an old installation interfering?

What should be done except `sudo apt-get remove mnemosyne` to remove archaic packaged version (I did it already)?

**Comment by pbienst** [comment]
Did you by any chance to try to install a previous version from source / github, which is still lying around? It's worthwhile deleting the egg files / mnemosyne directory in your active site-packages directory.

Since I cannot reproduce this (the github linux build runs fine, as does my own Windows build), I'm afraid I cannot really contribute many other things myself...

**Comment by matkoniecz** [comment]
`/usr/lib/python2.7/dist-packages` contains packages with system `mnemosyne` package installed.

Other folders

```
python -m site
sys.path = [
    '/home/mateusz',
    '/usr/local/lib/python2.7/dist-packages/webcolors-1.7-py2.7.egg',
    '/usr/local/lib/python2.7/dist-packages/kdtree-0.15-py2.7.egg',
    '/usr/lib/python2.7/dist-packages',
    '/home/mateusz/Documents/install_moje/python_packages',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-x86_64-linux-gnu',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/home/mateusz/.local/lib/python2.7/site-packages',
    '/usr/local/lib/python2.7/dist-packages',
    '/usr/lib/python2.7/dist-packages/PILcompat',
    '/usr/lib/python2.7/dist-packages/gst-0.10',
    '/usr/lib/python2.7/dist-packages/gtk-2.0',
]
USER_BASE: '/home/mateusz/.local' (exists)
USER_SITE: '/home/mateusz/.local/lib/python2.7/site-packages' (exists)
ENABLE_USER_SITE: True
```

are not containing folders with names starting from mnemosyne.

`/usr/lib/python2.7` is not containing also files with mnemosyne prefix.

I checked also

```
sys.path = [
    '/home/mateusz',
    '/home/mateusz/Documents/install_moje/python_packages',
    '/usr/lib/python35.zip',
    '/usr/lib/python3.5',
    '/usr/lib/python3.5/plat-x86_64-linux-gnu',
    '/usr/lib/python3.5/lib-dynload',
    '/home/mateusz/.local/lib/python3.5/site-packages',
    '/usr/local/lib/python3.5/dist-packages',
    '/usr/local/lib/python3.5/dist-packages/Mnemosyne-2.6.1-py3.5.egg',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/mateusz/.local' (exists)
USER_SITE: '/home/mateusz/.local/lib/python3.5/site-packages' (exists)
ENABLE_USER_SITE: True
```

`/usr/local/lib/python3.5/dist-packages` had something, running `sudo pip3 uninstall mnemosyne` twice removed both `Mnemosyne-2.6.1` and `Mnemosyne-2.6`.

I started tests again.

Now all tests completed.

**Comment by matkoniecz** [comment]
Thanks for the help! Though I am unsure why tests were fragile to files outside repo.
